[package]
name = "MangaYouKnow"
version = "0.6.0"
description = "A manga app!"
authors = ["ReiLoko4"]
license = "MIT"
repository = "https://github.com/manga-you-know/desktop"
edition = "2021"
rust-version = "1.84.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "lib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde_json = "1.0"
base64 = "0.21"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "2", features = ["protocol-asset", "tray-icon", "image-png", "image-ico"] }
tauri-plugin-sql = { version = "2", features = ["postgres", "sqlite"] }
tauri-plugin-log = "2.0.0-rc"
tauri-plugin-notification = { version = "2", features = [ "windows7-compat"] }
tauri-plugin-fs = "2"
tauri-plugin-store = "2"
tauri-plugin-dialog = "2"
tauri-plugin-process = "2"
tauri-plugin-shell = "2"
tauri-plugin-os = "2"

lazy_static = "1.5.0"
once_cell = "1.20.2"
tauri-plugin-clipboard = "2.1.11"
tauri-plugin-http = { version = "2", features = [ "unsafe-headers" ] }

[target."cfg(not(any(target_os = \"android\", target_os = \"ios\")))".dependencies]
tauri-plugin-autostart = "2"
tauri-plugin-cli = "2"
tauri-plugin-global-shortcut = "2"
tauri-plugin-single-instance = "2"
tauri-plugin-window-state = "2"
tauri-plugin-drpc = "0.1.6"
tauri-plugin-updater = "2"

